---
# tasks file for ansible-role-jicofo

- name: install base packages
  apt:
      pkg:
      - ufw
      - bmon
      - htop
      - default-jre
      - vim

- name: configure firewall rules
  ufw:
      rule: "{{ item.rule }}"
      port: "{{ item.port }}"
      proto: "{{ item.proto }}"
  with_items:
      - { rule: 'allow', port: '22', proto: 'tcp' }

- name: set logging
  ufw:
    logging: 'off'

- name: set ufw policy
  ufw:
    state: enabled
    policy: deny

- import_tasks: jitsi-repo.yaml

- name: install jicofo
  apt:
      name: jicofo
      state: latest

- name: deploy jicofo sip-communicator template
  template:
      src: templates/sip-communicator.properties.j2
      dest: /etc/jitsi/jicofo/sip-communicator.properties
  notify: restart jicofo service

# - name: make sure new jicofo settings are not used for now
#   file:
#     path: /etc/jitsi/jicofo/jicofo.conf
#     state: absent
#   notify: restart jicofo service

- name: deploy jicofo new settings template
  template:
    src: templates/jicofo.conf.j2
    dest: /etc/jitsi/jicofo/jicofo.conf
  notify: restart jicofo service

- name: deploy jicofo config template
  template:
      src: templates/config.j2
      dest: /etc/jitsi/jicofo/config
  notify: restart jicofo service

- when: prosody_host != 'localhost'
  block:

    - name: read certificate from prosody
      command: cat /var/lib/prosody/{{ jitsi_domain }}.crt
      register: read_certificate_from_prosody
      delegate_to: "{{ prosody_host }}"
      changed_when: false


    - name: write certificate from prosody in local certificate store
      copy:
        content: "{{read_certificate_from_prosody.stdout}}"
        dest: /usr/local/share/ca-certificates/{{ jitsi_domain }}.crt
      notify:
        - update-ca-certificates
        - restart jicofo service

    - name: read auth certificate from prosody
      command: cat /var/lib/prosody/{{ jitsi_auth_domain }}.crt
      register: read_auth_certificate_from_prosody
      delegate_to: "{{ prosody_host }}"
      changed_when: false

    - name: write auth certificate from prosody in local certificate store
      copy:
        content: "{{read_auth_certificate_from_prosody.stdout}}"
        dest: /usr/local/share/ca-certificates/{{ jitsi_auth_domain }}.crt
      notify:
        - update-ca-certificates
        - restart jicofo service

- name: enable jicofo service
  systemd:
      name: jicofo
      enabled: yes
